// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwstiburwrctiqleqebk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13c3RpYnVyd3JjdGlxbGVxZWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTA3MjAsImV4cCI6MjA2NDI4NjcyMH0.V579U1NN8m6Y4CPQUGwUIfsMWZVInQ9oBkIPYspmeYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);